name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build C++ Service
        working-directory: ./cpp-algos
        run: docker build -t cpp-algos-test .

      - name: Build Backend
        working-directory: ./backend
        run: docker build -t backend-test .

      - name: Build Frontend
        working-directory: ./frontend
        run: docker build -t frontend-test .